### ISSUE TITLE
Cannot find Register Page

### ISSUE THREAD

**Issue by Archan17** [idurar/idurar-erp-crm#1003]
I have cloned this repository and set up all the things which are required 

When i have run the file i am redirected to the sign in page where i can't find the link to register which is there in the deployed version

<img width="1437" alt="Screenshot 2024-03-08 at 1 48 58 PM" src="https://github.com/idurar/idurar-erp-crm/assets/100855291/b6e1dc71-7777-4c94-b932-89f15f1e17ca">

**Comment by drethedevjs** [comment]
@Archan17 Can you find the link in the code? It could be wrapped inside of a condition.

**Comment by AbhishekGurav** [comment]
@Archan17 The admin credentials are inside setup.jsx located in src>setup>setup.jsx. 

If you've run `npm run setup` during the installation then logging in with those credentials won't be an issue.

You can find more details in [this comment](https://github.com/idurar/idurar-erp-crm/issues/983#issuecomment-1970783759) Hope it helps!
