### ISSUE TITLE
Add East Caribbean Dollar Support

### ISSUE THREAD

**Issue by RuiSiang** [idurar/idurar-erp-crm#1054]
**Is your feature request related to a problem? Please describe.**
East Caribbean Dollar has fixed exchange to USD, and is the main currency in the Caribbeans. I don't like keep calculating the amount by hand

**Describe the solution you'd like**
Add East Caribbean Dollar in the Currency Code and other fields

**Describe alternatives you've considered**
Manual calculate EC to USD

**Additional context**
N/A

**Comment by dimple06varshney** [comment]
Hi, @RuiSiang 
Correct me if I am wrong. Do you mean while we add currencies there is no currency code available for the East Caribbean Dollar(i.e. XCD), so we can't add it? 
Solution - Add East Caribbean Dollar in the Currency Code

I want to work on this issue. Could you please assign this ticket to me? 
Thanks

**Comment by dimple06varshney** [comment]
@RuiSiang I have fixed the issue in my local. Now Currency can be added for XCD. I created one invoice with the same currency further to test it. 
Attached are screenshots for your reference. Please review. Let me know if there is something else or if I understood wrong. 
Please assign this ticket to me. 
Thanks
<img width="1087" alt="Screenshot 2024-04-11 at 3 06 11 PM" src="https://github.com/idurar/idurar-erp-crm/assets/87027688/4768ce8c-9974-4e39-8d9e-af95de80dd45">
<img width="1094" alt="Screenshot 2024-04-11 at 3 06 35 PM" src="https://github.com/idurar/idurar-erp-crm/assets/87027688/3fc2d100-14e5-4911-bd9f-9207e0cc3ac8">

**Comment by dimple06varshney** [comment]
Hi, @salahlalami Could you please review the PR? 
Thanks
