### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by rohanb273** [idurar/idurar-erp-crm#1056]
I want login details. As there is no option for creating new user. 
![6](https://github.com/idurar/idurar-erp-crm/assets/154302002/92d47728-e69e-470d-b477-e13c1698654f)

**Comment by dimple06varshney** [comment]
Hi, @rohanb273 If you just cloned and followed the steps listed in how to contribute readme. 
Create your MongoDB database cluster and add in.env (backend). 
install dependencies by running `npm i`
run `npm run setup`. It creates all required datasets in your database. 
In the setup file, you can find a password (**admin123**) and email (**admin@demo.com**). 

I hope it will help you. :)

**Comment by rohanb273** [comment]
Thanks @dimple06varshney

**Comment by rohanb273** [comment]
Thanks @dimple06varshney
