### ISSUE TITLE
Phone field accepts any character

### ISSUE THREAD

**Issue by yosrinajar** [idurar/idurar-erp-crm#1089]
**Describe the bug**
I can write any character in the phone option in companies' section, and also in the peoples' section.

**To Reproduce**
1. Go to 'companies'
2. Click on 'Add new company'
3. Write anything on the phone
4. Fill the required fields
5. Click on Submit.
6. You can do the same thing for the 'peoples' section

**Expected behavior**
It shouldn't be able to let me add anything other than a phone number

**Screenshots**
![image](https://github.com/idurar/idurar-erp-crm/assets/97942096/758b9bb0-7262-4264-b717-e39979343036)

**Comment by Sooraj002** [comment]
I would like to fix this issue.

**Comment by yosrinajar** [comment]
> I would like to fix this issue.

It's already fixed under this PR #1073
