### ISSUE TITLE
Provide Default Login Credentials or Instructions for Accessing Application

### ISSUE THREAD

**Issue by NandaniThakur** [idurar/idurar-erp-crm#1120]
Issue Description:
The current state of the repository lacks default login credentials or instructions for accessing the application. This presents a barrier to users or contributors who wish to test or evaluate the application but are unable to log in due to the absence of login credentials.

![image](https://github.com/idurar/idurar-erp-crm/assets/79366385/6ff569fa-591a-4257-9d15-674d477ad6a7)
Without login credentials, users are unable to access the application to test its functionality or provide feedback.

Provide default login credentials: Consider adding default login credentials (username/password) to the README or documentation to facilitate access for testing purposes.
or
Offer instructions for accessing the application: Alternatively, provide clear instructions on how users can access the application, whether through setting up their own credentials locally or using a demo account.

**Comment by MSNoorul** [comment]
username : admin@demo.com - password : admin123 this is the default login

**Comment by NandaniThakur** [comment]
I have used these credentials before too but nothing happened. 
let me show you.
here is the username and password provided by you .
![image](https://github.com/idurar/idurar-erp-crm/assets/79366385/b29825f8-df29-47b1-9322-f00013fff807)
but still show the same error.
![image](https://github.com/idurar/idurar-erp-crm/assets/79366385/cdf2d7ec-d4c0-45f9-9aea-3d2c44291072)

**Comment by sidhuiwnl** [comment]
It works for me
![Uploading IDURAR ERP CRM _ Open Code Source - Google Chrome 6_2_2024 1_51_47 PM (1).png…]()

**Comment by sidhuiwnl** [comment]
it works for me
![IDURAR ERP CRM _ Open Code Source - Google Chrome 6_2_2024 1_51_47 PM (1)](https://github.com/idurar/idurar-erp-crm/assets/95430324/4a2ffb83-6eab-45e3-94ea-a8a8cf003686)

**Comment by NandaniThakur** [comment]
Solved !!! 
I tried uninstalling project and then again Installed It. Used the above credentials and it worked.
Thanks for the help.
