### ISSUE TITLE
[ERR] Refresh Problem

### ISSUE THREAD

**Issue by AbdelattyBadwy16** [idurar/idurar-erp-crm#1157]
**Describe the bug**
when i refresh the page the website move me to the login page and break auth .

**To Reproduce**
1. Go to 'official website'.
2. login.
3. will see the home page.
4. refresh the page.
5. see error (it redirect you to the login page).

**Expected behavior**
when i refresh the page it stay auth and in the same page.

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser edge

**Comment by neehhaa06** [comment]
Hello!! @AbdelattyBadwy16 :)
```
To fix the issue, ensure authentication tokens are stored persistently in cookies or local storage. Validate tokens correctly on the server and update client-side code to handle authentication state after a refresh. Also, check and adjust session expiration settings as needed.
```

**Comment by avishusa** [comment]
I have tried to reproduce this issue but I think it has resolved by someone.

**Comment by Slacky300** [comment]
@AbdelattyBadwy16, could you please verify once more? In my situation, the login remains persistent upon page refresh.
