### ISSUE TITLE
can not login to the application

### ISSUE THREAD

**Issue by mituBarua** [idurar/idurar-erp-crm#164]
all the .variables.env files are same except database url and
api_url is : 'http://localhost:8888/api/'
after clicking login it gives this error "Cannot read property '_id' of null"
p.s I have add a object document named admins with email : admin@demo.com and pass admin123

**Comment by jeffreytgilbert** [comment]
This is reproducible on my machine using Safari on macOS Monterey. Works in Chrome.

**Comment by hiql** [comment]
Safari doesn't send cookies to the server if you set the cookie "secure: true" after you logged in.
It only works in https requests.

**Comment by salahlalami** [comment]
@jeffreytgilbert @hiql @mituBarua 
Cookies bugs on safari , fixed
