### ISSUE TITLE
Is there no UI here?

### ISSUE THREAD

**Issue by delcooper11** [idurar/idurar-erp-crm#184]
Is this meant to just be a backend? I don't see a way to load the UI used in the example. If this is the case please improve the setup documentation to indicate that.

**Comment by zeeshanibnali** [comment]
Both the front-end and back-end can be found here itself.
To load the front-end code though, you will need to go into the front end folder from the root directory.
`cd frontend`
Then, install the packages using your package manager
`yarn` or `npm install`
And finally:
`yarn start` or `npm run start`
or use the dev command:
`yarn start:dev` or `npm run start:dev`

**Comment by polymahh** [comment]
@delcooper11 a new guide on how to setup the project was added in the readme file
