### ISSUE TITLE
register button not working

### ISSUE THREAD

**Issue by anuragasawa20** [idurar/idurar-erp-crm#187]
on clicking register at sign in page there is not any sign up form I want to create it with verification email

**Comment by ujjwalpandey922** [comment]
Hi,
Can I work on this??

**Comment by anuragasawa20** [comment]
actually I have been started working on it.have you created something
related to it.

**Comment by N-NeelPatel** [comment]
this same issue has already been raised. https://github.com/idurar/idurar-erp-crm/issues/178

**Comment by jaiswalshash** [comment]
Hello guys!

I don't think that's an issue, see the code below
`Or <a href="">register now!</a>`
It was meant to work like that. Correct me if I'm wrong.

**Comment by anuragasawa20** [comment]
yes It means to add the functionality of register

**Comment by anuragasawa20** [comment]
Yes, you can do that.

**Comment by Vishrut19** [comment]
Hey! I was trying to run your project but I feel 2 things. Firstly,the documentation is not so good as it doesn't clearly states about to setup the project and run it and also, I feel that the website right now is very very static. 
So, for the first part I am getting some errors. Can someone help? 
Also, is there any slack and discord channel for fast communication?

**Comment by hrutik7** [comment]
yes @Vishrut19 I agree to your communication point
@idurar can we do something regarding docs , slack/discord  ? 
so that people who are interested in project can contribute

**Comment by Vishrut19** [comment]
> yes @Vishrut19 I agree to your communication point @idurar can we do something regarding docs , slack/discord ? so that people who are interested in project can contribute

Thanks for acknowledging it @hrutik7 and also please acknowledge it @idurar

**Comment by Vishrut19** [comment]
Hello, @hrutik7 @anuragasawa20 any update?

**Comment by polymahh** [comment]
hello everyone new readme file added and contributing file too
this issue has already been raised. https://github.com/idurar/idurar-erp-crm/issues/178
this issue will be closed please follow the new guide to run the project locally and test it
any help is appreciated
