### ISSUE TITLE
cursor is not changing to pointer

### ISSUE THREAD

**Issue by kartikp962** [idurar/idurar-erp-crm#189]
on the dashboard, cursor is not changing to pointer when hovering over notifications, toggle and username photo.

**Comment by zeeshanibnali** [comment]
Done!

Created a pull request: https://github.com/idurar/idurar-erp-crm/pull/190

Hopefully it will get resolved soon in sha Allah.

**Comment by Vishrut19** [comment]
Hey! Is this issue resolved?

**Comment by polymahh** [comment]
this issue is fixed in this [PR](https://github.com/idurar/idurar-erp-crm/pull/235)

**Comment by salahlalami** [comment]
@Vishrut19 , you are welcome to work on this issue

**Comment by Vishrut19** [comment]
> @Vishrut19 , you are welcome to work on this issue

Sure and thanks for giving me this opportunity @salahlalami

**Comment by akshit-dev101** [comment]
i would like to work on this.

**Comment by salahlalami** [comment]
you are welcome to contribute ,
here contribution guide https://github.com/idurar/idurar-erp-crm/blob/master/CONTRIBUTING.md

**Comment by Vishrut19** [comment]
I am already working on it. So, please assign me @salahlalami

**Comment by Vishrut19** [comment]
Raised the PR. Please review https://github.com/idurar/idurar-erp-crm/pull/289 - @salahlalami
