### ISSUE TITLE
How to contribute (frontend)?

### ISSUE THREAD

**Issue by ankush981** [idurar/idurar-erp-crm#191]
Hello, this looks like a nice, not-too-complex project to contribute to, but I was wondering how to go about it. I'm interested in the frontend side, but there don't seem to be too many issues and stuff is already assigned to people. Any suggestions? 🥲

**Comment by polymahh** [comment]
hello @ankush981 a new guide readme was added 
and contributing file was added too 
a good way to help is to test the project and find issues
and we will be sure to add beginner friendly tag later
