### ISSUE TITLE
Destroy Token after logout

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#197]
in Backend , Auth Token should be destroyed after logout , ex : add it to blacklist

**Comment by sameep-sehgal** [comment]
Hey salahlalami, how do you want to implement the blacklist? We can store the token in MongoDB or Redis(this will require Redis implementation but wont have to hit DB for every request) when user hits logout and the add this check on token in isValidAdminToken

**Comment by ajmanisameer** [comment]
> in Backend , Auth Token should be destroyed after logout , ex : add it to blacklist

Created a pull request.

**Comment by subhrajitMukherje** [comment]
Hey salahlalami, how do you want to implement the blacklist? We can store the token in MongoDB or Redis when user hits logout and the add this check on token in isValidAdminToken

**Comment by piyushjha0409** [comment]
> in Backend , Auth Token should be destroyed after logout , ex : add it to blacklist

Do we have to make a blacklist table in the database?
