### ISSUE TITLE
Missing CONTRIBUTING.MD readme.

### ISSUE THREAD

**Issue by tdogubo** [idurar/idurar-erp-crm#199]
Your project looks awesome and I am interested in contributing to it but the `contributing readme` is missing. 
Adding that would make onboarding and rendering help easier.

**Comment by RitikSinha** [comment]
hello @salahlalami ,
 I'm eager to make a positive contribution. However, I noticed that the readme file, which is typically the go-to resource for getting started, seems to be missing.

I believe having a comprehensive readme is crucial for new contributors like myself to understand the project's goals, structure, and guidelines. It provides a solid foundation and helps us align our efforts effectively.

Would it be possible for someone knowledgeable about the project to kindly provide some guidance on how to get started? It would be immensely helpful to receive an overview of the project, its objectives, and any specific instructions or requirements for contributing.

Thank you all for your time and consideration. I genuinely appreciate your assistance and I'm excited to begin contributing to this project.

**Comment by polymahh** [comment]
hello @RitikSinha @tdogubo thank you for your interest in the project 
a new readme and contribution files were added make sure to check it out
