### ISSUE TITLE
capitalize the label in adding the employee form

### ISSUE THREAD

**Issue by VenomFate-619** [idurar/idurar-erp-crm#210]
capitalize the label in adding the employee form
![image](https://github.com/idurar/idurar-erp-crm/assets/67755128/b76948c2-b2fb-4700-b2af-561b7532f57b)
![image](https://github.com/idurar/idurar-erp-crm/assets/67755128/d8882467-429d-41e6-a89b-174a06864b07)

it should something like this

![image](https://github.com/idurar/idurar-erp-crm/assets/67755128/3766dcb8-954f-4d35-8fc5-b31131ab1e9a)

**Comment by subhrajitMukherje** [comment]
Hey, Milanrai09 I wished to work on this issue

**Comment by Vishrut19** [comment]
Hey! Can I work on this issue ?? @VenomFate-619

**Comment by Vishrut19** [comment]
Please assign me this issue @polymahh
