### ISSUE TITLE
Employee details still remains open even after delete Success

### ISSUE THREAD

**Issue by manassahoo-dev** [idurar/idurar-erp-crm#213]
Steps to reproduce:

1. Click on Customer link from the side bar.
2. Click on the three dots in any of the row. And then click either show/ Edit.
3. Click on Delete Button from the left panel.
4. Delete confirmation modal pop up comes.
5. After Delete Sucess, the left panel, which is the Customer Details one should auto close. Because the record is deleted from the system.

**Comment by LOGESH-B** [comment]
I am interested to work on this issue

**Comment by Darlio88** [comment]
@LOGESH-B, Have you started working on that issue

**Comment by LOGESH-B** [comment]
Yeah,I completed and done PR
