### ISSUE TITLE
Logo Click Redirects to Home Page - Navigation Issue

### ISSUE THREAD

**Issue by SainiAditya1** [idurar/idurar-erp-crm#215]
When clicking on the logo in the website , the website should redirect the user to the home page. However, the current implementation does not perform the desired navigation action.

Steps to reproduce:
Open the   website .
Navigate to any page within the application.
Click on the logo present in the header section.

I want to implement this if you want this .

**Comment by Darlio88** [comment]
My suggestion would be you implement that (logo click redirects to the home Page) and make a pull request

**Comment by JoshTeflon** [comment]
I can get this fixed.

**Comment by SainiAditya1** [comment]
@Darlio88 ok , I will implement it and make a PR .

**Comment by Vishrut19** [comment]
Hey! Can you please assign me this issue ?

**Comment by chandra1899** [comment]
can any one tell me how can i setup this project locally , because there is no info in readme file

**Comment by chandra1899** [comment]
> When clicking on the logo in the website , the website should redirect the user to the home page. However, the current implementation does not perform the desired navigation action.
> 
> Steps to reproduce: Open the website . Navigate to any page within the application. Click on the logo present in the header section.
> 
> I want to implement this if you want this .

U mean redirect to dashboard ??

**Comment by polymahh** [comment]
> can any one tell me how can i setup this project locally , because there is no info in readme file

This guide provides step-by-step instructions to run the project locally on your machine, 
@salahlalami this guide can be added to the readme or used in articles 

### Step 1: Create Your MongoDB Account and Database/Cluster

- Create your own MongoDB account by visiting the MongoDB website and signing up for a new account.

- Create a new database or cluster by following the instructions provided in the MongoDB documentation. Remember to note down the "Connect to your application URI" for the database, as you will need it later. Also, make sure to change <password> with your own password

- add your current IP address to the MongoDB database's IP whitelist to allow connections (this is needed whenever your ip changes)

### Step 2: Rename the Environment File
Locate the file named tmp.variables.env in the root directory of the project and rename it to .variables.env. This file will be used to store the necessary environment variables for the project to run.

### Step 3: Update MongoDB URI
In the .variables.env file, find the line that reads:

`DATABASE="your-mongodb-uri"`

Replace "your-mongodb-uri" with the actual URI of your MongoDB database. 

### Step 4: Install Backend Dependencies
In your terminal, navigate to the root directory of the project and run the following command to install the backend dependencies:

`npm install`

This command will install all the required packages specified in the package.json file.

### Step 5: Run Setup Script
While still in the root directory of the project, execute the following command to run the setup script:

`node setup/setup.js`

This setup script may perform necessary database migrations or any other initialization tasks required for the project.

### Step 6: Run the Backend Server
In the same terminal, run the following command to start the backend server:

`npm run dev`

This command will start the backend server, and it will listen for incoming requests.

### Step 7: Install Frontend Dependencies
Open a new terminal window , and run the following command to install the frontend dependencies:

`cd frontend`
`npm install`

This command will navigate to the frontend directory within the project and install all the required packages for the frontend.

### Step 8: Run the Frontend Server
After installing the frontend dependencies, run the following command in the same terminal to start the frontend server:

`npm run start`

This command will start the frontend server, and you'll be able to access the website on localhost:3000 in your web browser.

### If you encounter an OpenSSL error while running the frontend server, follow these additional steps:

- Run the following command in the terminal:

`export NODE_OPTIONS=--openssl-legacy-provider`

- Then, re-run the frontend server:

`npm run start`

### Website Login Credentials
Once the website is up and running, you can log in using the following credentials:

Username: admin@demo.com
Password: admin123

Now you should be all set to run the project locally on your machine and explore its features. If you encounter any issues or have questions, feel free to seek assistance in the project's github community . Happy coding!

**Comment by chandra1899** [comment]
backend is successfully running but i'm encountering error in running frontend.This is the error
<img width="776" alt="image" src="https://github.com/idurar/idurar-erp-crm/assets/101719497/5aa81a0e-2ad1-4ac5-8d11-1f6c88892200">

**Comment by polymahh** [comment]
yes that is the last part of my guide the openssl error follow the last two steps

**Comment by chandra1899** [comment]
> yes that is the last part of my guide the openssl error follow the last two steps

yes it is running and thank you for the help to setup this project locally.
