### ISSUE TITLE
[Enhancement ] Migrate to Redux ToolKit as Using Redux Core is now deprecated 

### ISSUE THREAD

**Issue by Onesco** [idurar/idurar-erp-crm#217]
As recommended by the Redux team as of today, the usage of the Redux core should only be used for learning purposes as the createStore function is already tagged deprecated. 
*"@deprecated
We recommend using the configureStore method of the @reduxjs/toolkit package, which replaces createStore.
Redux Toolkit is our recommended approach for writing Redux logic today, including store setup, reducers, data fetching, and more.
For more details, [please read this Redux docs page](https://redux.js.org/introduction/why-rtk-is-redux-today) ... You should not be using the redux core package by itself today, except for learning purposes. The createStore method from the core redux package will not be removed, **but we encourage all users to migrate to using Redux Toolkit for all Redux code.**"*

You could assign this to me if you see the need for this migration!

**Comment by i-supermario** [comment]
I would be interested in helping out for this too @salahlalami

**Comment by onfranciis** [comment]
I'm interested in this as well @salahlalami

**Comment by Vishrut19** [comment]
Can I work on it?

**Comment by salahlalami** [comment]
@Onesco Thank you for suggestion , we will do that in next upgrade , probably in one year
