### ISSUE TITLE
Favicon and other assets 

### ISSUE THREAD

**Issue by akindoju** [idurar/idurar-erp-crm#219]
Hi, I noticed there's no favicon, and the logo doesn't seem so clear. Can I work on this? @salahlalami

**Comment by salahlalami** [comment]
@akindoju sure, you are welcome to work on it , here some svg logo
![favicon](https://github.com/idurar/idurar-erp-crm/assets/136928179/3c0f53d5-f079-498f-9e15-f6200a5a5655)
![idurar-crm-erp](https://github.com/idurar/idurar-erp-crm/assets/136928179/c7114ccb-db88-4557-8868-98f70f6a09b7)

**Comment by akindoju** [comment]
Done @salahlalami, feel free to review and merge
