### ISSUE TITLE
Frontend: Help Button is not diplaying properly

### ISSUE THREAD

**Issue by LaansDole** [idurar/idurar-erp-crm#220]
There are some issues with the Help button at the bottom right corner. For example, when I go to We are Hiring page, the button glitched and disappear. In addition, the button is covering the bottom nav bar. Can I work on this @salahlalami

**Comment by Vishrut19** [comment]
Can I work on this issue?

**Comment by manan-upadhyay** [comment]
I am open to work on this as well!

**Comment by salahlalami** [comment]
There is no help button in IDURAR ERP CRM APP
