### ISSUE TITLE
Request to update README file and dockerize project

### ISSUE THREAD

**Issue by mdjamilkashemporosh** [idurar/idurar-erp-crm#223]
I recently came across your open-source project and was excited to try it out. However, I found that I had trouble getting it to work properly due to a lack of instructions in the README file.

I believe that updating the README file with more detailed and clear instructions would greatly benefit users like myself who are trying to use your project. Additionally, if possible, I think it would be great if the project could be dockerized to make it easier to set up and use.

Could you please consider updating the README file with more information on how to use the project properly, and also consider dockerizing the project if possible?

**Comment by rahullo** [comment]
I am also getting the same problem.

**Comment by polymahh** [comment]
@mdjamilkashemporosh i hope you fixed the problem
if not a new README file was added with a step by step guide
i'll consider this fixed if you are still facing problems can you please make a new
