### ISSUE TITLE
Send Invoice by mail Api Endpoint

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#227]

**Comment by rishavmehra** [comment]
Hey @salahlalami can please suggest me issues to work on. I can also contribute in backend and little bit in frontend(react) and DevOps monitoring/logging of the sytstem/build pipelines.

**Comment by Neeraja-Gadi** [comment]
Hey @salahlalami canyoujust eloborate on your requirement. I have prior experience for email generation using nodemailer.
