### ISSUE TITLE
Dark mode feature

### ISSUE THREAD

**Issue by Abhishek-Panwar-2004** [idurar/idurar-erp-crm#234]
It will be a good enhancement feature to add a dark mode feature and I am working on it.

**Comment by rahullo** [comment]
I am having problems starting this project due to a lack of instruction. can you help me with that?

**Comment by Abhishek-Panwar-2004** [comment]
What problem are you facing?

**Comment by rahullo** [comment]
I am not able to run this project on my local computer. I changed the Mongoose URL but still stuck. What should I do next after changing the mongoose url?

**Comment by Aman-Gupta-404** [comment]
Hey, please follow the steps mentioned here #247 

check files changed tab, you will be able to see all the steps required to run the app locally.

**Comment by salahlalami** [comment]
@Abhishek-Panwar-2004 thanks for sugession , but this not possible at moment , maybe next year when we upgrade to new antd version ,
