### ISSUE TITLE
Add Local Setup - Readme 

### ISSUE THREAD

**Issue by SergeOin** [idurar/idurar-erp-crm#241]
## Setup Guide

To run this project locally, follow these steps:

**1. Clone the repository:**

```bash
git clone https://github.com/idurar/idurar-erp-crm.git
cd idurar-erp-crm 
```
**Set up your database:**

This project uses MongoDB as the database. You need to create a cluster in MongoDB Atlas and a user with a username and password. Then, edit the `tmp.variables.env` file and replace the `DATABASE` value with your MongoDB URI. For example:

```bash
DATABASE = "mongodb+srv://username:password@clustername.mongodb.net/idurar"
```

After that, rename the file to `.variables.env`

**Install the dependencies and start the project:**

In the `idurar-erp-crm` folder, run:

```bash
npm install
npm start
```

In the `idurar-erp-crm/frontend` folder, run:

```bash
npm install
npm start
```

The project should be running on `http://localhost:3000`

**Comment by omfriyad** [comment]
I think the guide has been provided [here](https://github.com/idurar/idurar-erp-crm/pull/247) by @polymahh, it needs to merged.

**Comment by SergeOin** [comment]
Well seen, I had not noticed. I will close.
