### ISSUE TITLE
Create Invoice from Quotation

### ISSUE THREAD

**Issue by omfriyad** [idurar/idurar-erp-crm#242]
##### I think the ERP system really shines when you can convert a quotation to an invoice, This feature should have the following:
- A button on the quotation to convert it to an invoice will auto-update the quotation status.
- Or when the quotation status is accepted, it'll auto-trigger to create an invoice for that customer.
##### Bonus
- Sending emails to customers based on invoice creation.

**Comment by lazyfuhrer** [comment]
I'd like to work on this @omfriyad

**Comment by mohitkadwe19** [comment]
Hey @omfriyad , I'd like to work on this feature , kindly assign to me

**Comment by omfriyad** [comment]
@lazyfuhrer since you've asked first, go ahead and open a PR.

**Comment by lazyfuhrer** [comment]
Thanks

**Comment by omfriyad** [comment]
@lazyfuhrer  while you're working on it, can you also mention the PR here?

**Comment by lazyfuhrer** [comment]
Sure

**Comment by lazyfuhrer** [comment]
Check #253 @omfriyad

**Comment by salahlalami** [comment]
@lazyfuhrer  here current PR for this issue : https://github.com/idurar/idurar-erp-crm/pull/274
