### ISSUE TITLE
extracting current user information for the profile page

### ISSUE THREAD

**Issue by polymahh** [idurar/idurar-erp-crm#249]
name, surname , email and user role that will be displayed in the profile page

**Comment by lazyfuhrer** [comment]
Is anyone working or I can go ahead

**Comment by polymahh** [comment]
@lazyfuhrer this issue was assigned to @adeojoemmanuel
if he didnt start yet or want your help I'll be happy to assign it to you, but wait for his response

**Comment by chandra1899** [comment]
@adeojoemmanuel what is the progress on this issue ??

**Comment by adeojoemmanuel** [comment]
hwy @chandra1899 i already started working on it, i would submit a pr for it soon

**Comment by adeojoemmanuel** [comment]
checkout this pr https://github.com/idurar/idurar-erp-crm/pull/358/files

**Comment by polymahh** [comment]
@vinaybadgujar102  yes feel free to contribute
