### ISSUE TITLE
Write A Github Actions Pipeline to Test on Multipe Operating Systems

### ISSUE THREAD

**Issue by dapsavoie** [idurar/idurar-erp-crm#251]
Given users may have a variety of Operating systems on which they would use Idurar, I am proposing a simple github actions ci to test app is building across various systems. We can start with Windows, Ubuntu and MacOs. 

Proposed Solution:
Implement a GitHub Actions workflow that tests the app on multiple operating systems. This will help us catch any OS-specific bugs or issues early in the development process.

**Comment by salahlalami** [comment]
@dapsavoie Ok , you are welcome to contribute
