### ISSUE TITLE
Create Invoice from Quotation API

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#261]
Create new Quote api that can convert Quote to invoice :

From Quote Data , Create new invoice in Invoice table

**Comment by Elham-EN** [comment]
Hello brother @salahlalami, can you assign me to this issue please.

**Comment by salahlalami** [comment]
@Elham-EN , you are welcome to contribute and work on this issue

**Comment by Elham-EN** [comment]
Thank you, @salahlalami,  Could you please assign it to me? (Assignees )

**Comment by salahlalami** [comment]
@Elham-EN you can work here , but we found that we are unable to assigne issue to extern contributor.

Once you finish you can open PR
