### ISSUE TITLE
Add Button to convert quote to Invoice

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#262]
* Add button in quote datatable to convert quote to Invoice 
* Open new invoice edit page contain the new invoice data extracted from quote

This should be solved after #263 and #261

**Comment by Elham-EN** [comment]
@salahlalami can you assign me to this issue and also the backend part as well https://github.com/idurar/idurar-erp-crm/issues/261

**Comment by salahlalami** [comment]
@Elham-EN you can work here , but we found that we are unable to assigne issue to extern contributor.

Once you finish you can open PR
