### ISSUE TITLE
Dashboard Card : This month Total

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#264]
Create separate component for AnalyticsCard inside Dashboard Folder (* create Dashboard Folder)

and calculate amount

<img width="554" alt="Screenshot 2023-08-11 at 10 11 32 AM" src="https://github.com/idurar/idurar-erp-crm/assets/136928179/043147d0-b6ba-42cd-9354-203944b8c660">
<img width="542" alt="Screenshot 2023-08-11 at 10 11 50 AM" src="https://github.com/idurar/idurar-erp-crm/assets/136928179/d2d9579d-ddc9-41a5-afcf-7b4ebbc85fe8">

**Comment by Vishrut19** [comment]
Hey! Are you working on this issue or I can work on it?
