### ISSUE TITLE
Dashboard APi :   Customer Analytics Api 

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#267]
Create Api Analytics for customer , to be serve  Customer Analytics card in Dashboard  
<img width="286" alt="Screenshot 2023-08-11 at 10 25 34 AM" src="https://github.com/idurar/idurar-erp-crm/assets/136928179/bd1fe1d6-7c95-4aab-848f-01f1d98282df">

**Comment by anonymous4561** [comment]
@salahlalami  can i work on this?

**Comment by salahlalami** [comment]
you are welcome to contribute ,
here contribution guide https://github.com/idurar/idurar-erp-crm/blob/master/CONTRIBUTING.md
