### ISSUE TITLE
Responsive : DataTable Responsive on Tablet and Mobile

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#273]
Add css Responsive to DataTable for Tablet and Mobile ,
* Tablet and mobile should be same just on field per line

<img width="795" alt="Screenshot 2023-08-11 at 12 20 43 PM" src="https://github.com/idurar/idurar-erp-crm/assets/136928179/df3d48a1-972c-44a5-97b0-5d60fa09d3f5">

**Comment by Abhishek7Tech** [comment]
I would like to contribute if this issue is still open!

**Comment by polymahh** [comment]
@Abhishek7Tech feel free to contribute, i will try to make my own version that will be one row and it opens and reveals the other fields
try something innovative , we want a great user experience
