### ISSUE TITLE
Enhancing User Experience: Making the Dashboard Sidebar Sticky

### ISSUE THREAD

**Issue by rajgop1** [idurar/idurar-erp-crm#275]
Hello there! 🚀

I've been using the web app and noticed an opportunity to improve the user experience. I believe that implementing a sticky sidebar for the dashboard would be a fantastic enhancement. Currently, the sidebar doesn't stay visible as users scroll through the content, which can sometimes make navigation a bit cumbersome, especially when dealing with a lot of data.

Having a sticky sidebar would ensure that the navigation options and important features are always accessible, regardless of where users are on the page. This could lead to a smoother and more intuitive user experience.

If you're on board with this idea, I'd love to take the initiative and work on making this change. I think it could add a lot of value to the web app. Would you be open to me creating a pull request for this enhancement? I'm excited to contribute and make the dashboard even more user-friendly! 🌟

Looking forward to your thoughts on this. Let's collaborate to enhance the app's usability together! 🙌

![image](https://github.com/idurar/idurar-erp-crm/assets/97302657/d374a232-842e-4dfd-8819-cea35938d8d5)

**Comment by salahlalami** [comment]
@rajgop1 Sure , i will assign this for you

**Comment by rajgop1** [comment]
@salahlalami I have created a pull request. Could you please review it?

**Comment by Muhammad0320** [comment]
Please assign me for this task @salahlalami

**Comment by salahlalami** [comment]
hi @Muhammad0320 please check other issue , you can pick one and start to work on it https://github.com/idurar/idurar-erp-crm/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
