### ISSUE TITLE
Bug : notfound URL  redirect doesn't work

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#276]
Bug : notfound URL redirect doesn't work .

This was work correctly in previous version check here : notfound URL : https://demo-erp-crm.idurarapp.com/notfound

<img width="1097" alt="Screenshot 2023-08-11 at 2 59 10 PM" src="https://github.com/idurar/idurar-erp-crm/assets/136928179/3dc2c56b-50e6-4d1c-88f9-41a10773926c">

<img width="1097" alt="Screenshot 2023-08-11 at 3 02 28 PM" src="https://github.com/idurar/idurar-erp-crm/assets/136928179/920efb60-4a2a-4537-89e9-c9495c70c708">

**Comment by polymahh** [comment]
working on it

**Comment by salahlalami** [comment]
@polymahh check "demo" branch to see how it was work

**Comment by polymahh** [comment]
fixed with the help of @adeojoemmanuel
