### ISSUE TITLE
API : Replace all Invoice Quote payment  Calculation with Calculate Helper Method 

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#279]
Replace all  Calculation with Calculate Helper Method : 

* paymentInvoiceController
* invoiceController
* quoteController

Example : 

Convert 

```javascript
const changedAmount = currentAmount - previousAmount;
```

to

```javascript
const { calculate } = require('@/helpers');

const changedAmount = calculate.sub(currentAmount , previousAmount);
```

**Comment by anonymous4561** [comment]
let me work on this

**Comment by Onesco** [comment]
@salahlalami i would also like to work on this.

**Comment by anonymous4561** [comment]
@Onesco u can start working on this

**Comment by arpitnakrani** [comment]
if anyone is not working on this please assign it to me @salahlalami , thanks in advance

**Comment by arpitnakrani** [comment]
Implemented it in paymentinvoicecontroller , waiting for your permission to do it in other 2 controllers. thank you

**Comment by salahlalami** [comment]
issue is resolved
