### ISSUE TITLE
Add Profile Page

### ISSUE THREAD

**Issue by idurar** [idurar/idurar-erp-crm#28]

**Comment by hrutik7** [comment]
Hey @idurar can I work on this ?

**Comment by idurar** [comment]
Sure ! @hrutik7 🚀

**Comment by hrutik7** [comment]
will you please assign this issue to me ?

**Comment by hrutik7** [comment]
@idurar can we communicate on discord or slack ?
need to discuss few things before starting

**Comment by salahlalami** [comment]
@polymahh please work on this issue , create new profile page
