### ISSUE TITLE
Replace all Invoice Quote payment Calculation with Calculate Utils Method

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#280]
Replace all  Calculation with Calculate utils Method : 

Search in all erp component / modules , invoice , quote , payment

Example : 

Convert 

```javascript
const changedAmount = currentAmount - previousAmount;
```

to

```javascript
import calculate from '@/utils/calculate';

const changedAmount = calculate.sub(currentAmount , previousAmount);
```

**Comment by SumitMangrati** [comment]
I want to start my journey on open source contribution and I would like to work on this issues if you could assign me to work on this issues and guide me, it would be really helpful

**Comment by droffilc1** [comment]
@salahlalami I would like to take this issue on

**Comment by droffilc1** [comment]
@salahlalami I can't seem to find the calculation method mentioned above.

**Comment by salahlalami** [comment]
@droffilc1 , start work from "dev" branch
here contribution guide https://github.com/idurar/idurar-erp-crm/blob/master/CONTRIBUTING.md

**Comment by droffilc1** [comment]
> Replace all Calculation with Calculate utils Method :
> 
> Search in all erp component / modules , invoice , quote , payment
> 
> Example :
> 
> Convert
> 
> ```js
> const changedAmount = currentAmount - previousAmount;
> ```
> 
> to
> 
> ```js
> import calculate from '@/utils/calculate';
> 
> const changedAmount = calculate.sub(currentAmount , previousAmount);
> ```

@ Am talking about this. I can't find where this is implemented

**Comment by droffilc1** [comment]
> Replace all Calculation with Calculate utils Method :
> 
> Search in all erp component / modules , invoice , quote , payment
> 
> Example :
> 
> Convert
> 
> ```js
> const changedAmount = currentAmount - previousAmount;
> ```
> 
> to
> 
> ```js
> import calculate from '@/utils/calculate';
> 
> const changedAmount = calculate.sub(currentAmount , previousAmount);
> ```

Am talking about this. I can't find where it is implemented

**Comment by salahlalami** [comment]
@droffilc1 this is just example

**Comment by Kashif-Saleem-Ghuman** [comment]
@salahlalami  Hi, I can contribute to this issue without  being assigned , right?

**Comment by salahlalami** [comment]
@Kashif-Saleem-Ghuman , sure you can

**Comment by Kashif-Saleem-Ghuman** [comment]
> @Kashif-Saleem-Ghuman , sure you can

Thanks @salahlalami  I am on it

**Comment by salahlalami** [comment]
issue is resolved
