### ISSUE TITLE
Project Docker File

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#281]
IDURAR need Project Docker File

**Comment by anonymous4561** [comment]
Okay I will do this

**Comment by polymahh** [comment]
@anonymous4561 there is already a [branch ](https://github.com/idurar/idurar-erp-crm/pull/282) that is work in progress 
maybe you can see if it is correct  or you can find other issues to help with

**Comment by anonymous4561** [comment]
@polymahh Thanks For let me Know
