### ISSUE TITLE
Improper error handling in the form

### ISSUE THREAD

**Issue by Muhammad0320** [idurar/idurar-erp-crm#283]
I checked the app and I left the company input empty and the entered text into the phone input it submitted and what I expected was a kind of Error

Could you please assign me to handle this part and other parts also.

**Comment by Muhammad0320** [comment]
I will be glad if this issue can be assigned to me

**Comment by salahlalami** [comment]
sure you can only number to phone input, you can work on this

**Comment by Muhammad0320** [comment]
@salahlalami  thank you, will start working on it

**Comment by Muhammad0320** [comment]
I'm not able to login it said error 400 no account with this email has been registered

**Comment by polymahh** [comment]
when you go to  your mongodb data base and click browse collection do you see all the collections (admins, clients ...)
if not you have to run `node setup/setup.js again `

**Comment by Muhammad0320** [comment]
> @Muhammad0320 when you go to your mongodb data base and click browse collection do you see all the collections (admins, clients ...) if not you have to run `node setup/setup.js` again

okay sir

**Comment by Muhammad0320** [comment]
@polymahh  I've tried it's still not working

**Comment by Vishrut19** [comment]
Can I work on it? @polymahh

**Comment by chandra1899** [comment]
@Muhammad0320 if I left the company input empty the form is not submitted and it also displayed error , can u elaborate what is the issue.
