### ISSUE TITLE
[FEAT]: Color on Hover Animation on the 4 logos(Slack, Office, Google Cloud etc.)

### ISSUE THREAD

**Issue by SaketKaswa20** [idurar/idurar-erp-crm#284]
The logos of this brands should get coloured when the mouse is hovered on it.

**Comment by polymahh** [comment]
@SaketKaswa20  giving them a hover state will seem like they are clickable

**Comment by Abhishek7Tech** [comment]
I would like to contribute if this issue is still open!

**Comment by SaketKaswa20** [comment]
@polymahh Not necessarily, might be better for aesthetics ig!

**Comment by Kr-Upendra** [comment]
Is it still open?
