### ISSUE TITLE
Navigation on Mobile phone 

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#288]
* Make navigation close by default on mobile device size
* hide Content part when navigation is open on mobile device size
* Close navigation when we click on content  on mobile device size
* add css rules to Navigation  on mobile device size : 
`
height: 100%;
    overflow-y: scroll;
`
<img width="531" alt="Screenshot 2023-08-12 at 4 29 17 PM" src="https://github.com/idurar/idurar-erp-crm/assets/136928179/ac872e89-4726-4fa0-801f-66c2fbc673ec">

**Comment by agamswaroop619** [comment]
Hey @salahlalami , I can help with this issue. Please assign it to me!

**Comment by salahlalami** [comment]
@agamswaroop619  you are welcome to contribute ,
here contribution guide https://github.com/idurar/idurar-erp-crm/blob/master/CONTRIBUTING.md

**Comment by Abhishek7Tech** [comment]
I would like to contribute if this issue is still open!
