### ISSUE TITLE
Invalid number on payment/invoice page

### ISSUE THREAD

**Issue by OvilashMoitra** [idurar/idurar-erp-crm#302]
@salahlalami can i contribute on this.
/payment/invoice
is this  url number of invoice can be setting 0.

**Comment by OvilashMoitra** [comment]
@polymahh can i please contribute on thsi

**Comment by polymahh** [comment]
@OvilashMoitra  yes feel free to help
but what number are you referring to ?
![image](https://github.com/idurar/idurar-erp-crm/assets/15654652/c0b7ef5a-c3e8-4afa-a83e-dc405fa27a3c)

**Comment by OvilashMoitra** [comment]
<img width="1709" alt="image" src="https://github.com/idurar/idurar-erp-crm/assets/96794196/ad06ca45-68e8-45d3-85ba-fa5a59e55a85">

This is the problem I am addressing.

**Comment by polymahh** [comment]
you mean setting the invoice number to a negative number ?

**Comment by OvilashMoitra** [comment]
yes. Can i change it.

**Comment by polymahh** [comment]
yh feel free to collaborate

**Comment by OvilashMoitra** [comment]
On it. Thanks it means a lot to me.

**Comment by polymahh** [comment]
fixed here https://github.com/idurar/idurar-erp-crm/pull/311
