### ISSUE TITLE
the menu is not highlighted 

### ISSUE THREAD

**Issue by polymahh** [idurar/idurar-erp-crm#306]
the menu is not highlighted if you access it with the link

![image](https://github.com/idurar/idurar-erp-crm/assets/15654652/d1e6bce2-72d6-4aaa-8deb-8cfea495b68f)

**Comment by ashmeetsmonga** [comment]
I would like to work on this issue

**Comment by polymahh** [comment]
@ashmeetsmonga  yes feel free to contribute, we are using ant library menu

**Comment by Vishrut19** [comment]
Hey! Can I work on this issue?
