### ISSUE TITLE
Creating Duplicate Customer- backend issue

### ISSUE THREAD

**Issue by OvilashMoitra** [idurar/idurar-erp-crm#312]
<img width="1710" alt="image" src="https://github.com/idurar/idurar-erp-crm/assets/96794196/717376ce-f375-4a4d-a8e7-762df237fec3">
Can i create unique constraint with email and phone number and company name if needed.

**Comment by polymahh** [comment]
@OvilashMoitra what if the managers have the same name or surname , and some companies have same name only email cannot be the same

**Comment by OvilashMoitra** [comment]
Well that's a problem then.One manager can serve at two company. But if the company name exactly same then during the invoice creation it will create confusion to find the right company.  Any suggestion

**Comment by OvilashMoitra** [comment]
Alright I will add the constraint on the backend.

**Comment by Vayras** [comment]
Hi, Can I contribute towards this @polymahh @OvilashMoitra
