### ISSUE TITLE
[bug]: N should be capitalize in number field 

### ISSUE THREAD

**Issue by Nam1001** [idurar/idurar-erp-crm#318]
Problem
In the payment invoice section when we look at the table then we can observe that
"N" should be capitalize in number field the ie "number"--->"Number".

How to reproduce
1.open the website
2.go to payment invoice section
3.observe the 1st field of the table

Here is the screenshot
![image](https://github.com/idurar/idurar-erp-crm/assets/96697397/c29e62a1-e30d-44a8-9ba9-03eef46905e4)

**Comment by polymahh** [comment]
@Nam1001 thank you for pointing that out 
here is more so we can fix all capitalize fisrt letter issues here 
![image](https://github.com/idurar/idurar-erp-crm/assets/15654652/45155252-74c0-46f5-9da2-40e2c75962a4)
![image](https://github.com/idurar/idurar-erp-crm/assets/15654652/e4565fe2-e5f1-4903-ae74-8923ccb94cd7)
![image](https://github.com/idurar/idurar-erp-crm/assets/15654652/07e12272-bfa2-47b1-8010-18be49cc6f97)
![image](https://github.com/idurar/idurar-erp-crm/assets/15654652/4f0cb06e-f90e-46db-bc65-30c9b0cd82f4)

**Comment by alceil** [comment]
Can I work on this @polymahh

**Comment by polymahh** [comment]
@alceil  yh feel free to contribute
