### ISSUE TITLE
Dashboard not responsive on mobile devices!

### ISSUE THREAD

**Issue by elhussienalmasri** [idurar/idurar-erp-crm#323]
Dashboard  not responsive because Side Menu is open on mobile devices , and also 
when close the side menu some components not responsive also like Recent Invoices and
Recent Quotes, some columns disappear like Status.

please assign this issue to me.

![Screenshot_1](https://github.com/idurar/idurar-erp-crm/assets/90080237/abd09543-7f8e-4cd7-b9eb-dcb8e2590f22)
 ![Screenshot_2](https://github.com/idurar/idurar-erp-crm/assets/90080237/10050eae-c308-4061-8f7a-f73c7e35c4d8)
![Screenshot_3](https://github.com/idurar/idurar-erp-crm/assets/90080237/ab51d90b-5714-41dd-b06e-582a032596bf)

**Comment by polymahh** [comment]
thank you @elhussienalmasri for pointing these out 
responsiveness is still in progress we already have PRs  that fix the navigation on mobile waiting to be approved
next week i will add some more issues

**Comment by elhussienalmasri** [comment]
Thanks for reply @polymahh , but after the navigation is closed some Component not responsive  also like "Recent Invoices", and also under customer route not responsive also   ,
so can I work on it after the navigation fixed . or this issue also some one work on it .

![Screenshot_5](https://github.com/idurar/idurar-erp-crm/assets/90080237/5384d736-b76e-42c8-95c2-655e46f6dd18)
![Screenshot_4](https://github.com/idurar/idurar-erp-crm/assets/90080237/e8678d77-7e46-4991-9686-5e090b8982b9)
this Screenshots  show  customer route not responsive ,some columns disappear like "Email"
on mobile devices.

**Comment by polymahh** [comment]
yes  the navigation is already fixed you can check it in the dev branch i think you have to update your fork
also the table I am working on it here is the issue for it https://github.com/idurar/idurar-erp-crm/issues/273
so next week when all of these will be approved i will do more issues

**Comment by elhussienalmasri** [comment]
really I don ,t see it , so sorry for that .
