### ISSUE TITLE
the sidePanel is wider than the screen on mobile

### ISSUE THREAD

**Issue by polymahh** [idurar/idurar-erp-crm#333]
on some mobile screens the sidePanel can become wider than the screen we need to set it it's max-width

![image](https://github.com/idurar/idurar-erp-crm/assets/15654652/bf9f0280-bb13-426c-9cce-51d345c6f644)

go to customer
click on add new customer

**Comment by Sky-De** [comment]
@polymahh assign this to me , i would like fix it 
Thanks

**Comment by Vishrut19** [comment]
I want to work on it. Please assign me

**Comment by polymahh** [comment]
yes @Sky-De i don't have the ability to assign but feel free to contribute

**Comment by brunovjk** [comment]
Created draft pull request #377, can you check @polymahh? Thank you :D
