### ISSUE TITLE
create a dropdown for notifications

### ISSUE THREAD

**Issue by polymahh** [idurar/idurar-erp-crm#339]
#### create a dropdown for notifications with some fake notifications 
- it should follow the website design , make it similar to the profile dropdown
- every notification should have a remove button to delete it from the list
![image](https://github.com/idurar/idurar-erp-crm/assets/15654652/d9c39bc0-95db-4e5b-b602-1c07400ff904)

**Comment by Sky-De** [comment]
@polymahh hi, i would like to work on this, please assign this to me
Thank you

**Comment by polymahh** [comment]
@Sky-De yes feel free to contribute

**Comment by sidgaikwad** [comment]
@polymahh Can you please check my changes
