### ISSUE TITLE
Some standards issue / input validation

### ISSUE THREAD

**Issue by VishnuKaniyamvayal** [idurar/idurar-erp-crm#341]
I have Noticed some minor changes required in the  Add new employee field
1.
![Screenshot (227)](https://github.com/idurar/idurar-erp-crm/assets/111561574/e90bb98b-add9-4856-b1d3-5617fb3c75c0)

The data will be more accurate if there is a number validation ( Allow only numbers )  in phone number field 

 2.
![Screenshot (228)](https://github.com/idurar/idurar-erp-crm/assets/111561574/a0ebc005-36db-4c75-875d-36163af2878d)
The first character of every field label should be an uppercase letter.

**Comment by polymahh** [comment]
@VishnuKaniyamvayal this PR https://github.com/idurar/idurar-erp-crm/pull/329 will fix the uppercase problem 
and feel free to add validation for the phone number if you can

**Comment by polymahh** [comment]
we can also fix phone number field in the emplyee form
![image](https://github.com/idurar/idurar-erp-crm/assets/15654652/c0b6a70f-cdcb-4cd7-9f6e-ecc90932b5ee)
and also the Email field in the admin form
![image](https://github.com/idurar/idurar-erp-crm/assets/15654652/d67cbe48-6e40-415d-87d2-9f684e42a343)

**Comment by rkmdCodes** [comment]
can i take this ?

**Comment by rkmdCodes** [comment]
hi @polymahh @salahlalami sir,
Please review PR #342 which is closing this issue

**Comment by polymahh** [comment]
for phone number we need a validator of some sort because phone numbers are not strictly just numbers
some have + , - , ()

**Comment by rkmdCodes** [comment]
hi @polymahh thank you for reviewing my PR
I have created a new PR #348 

Created a new branch as stated in contributing.md
Removed Unrelated Changes to this issue 
Updated the Phone Numbers Validation

Thanks
