### ISSUE TITLE
[feat] Typescript

### ISSUE THREAD

**Issue by MattGould1** [idurar/idurar-erp-crm#347]
Hey,

What are your opinions on TypeScript? I feel that especially for the backend that type safety is a huge boon as a project grows and that the overhead is minimal but, do we want to spend time adding TS vs adding features at this stage?

**Comment by takiuddinahmed** [comment]
Integrating TypeScript seems to be a worthwhile investment of time. TypeScript effectively minimizes typing and syntax errors, subsequently reducing debugging efforts. This improvement in the development process not only enhances overall efficiency but also contributes to a reduction in bugs.

**Comment by polymahh** [comment]
@MattGould1 @takiuddinahmed yes at this stage we are adding final features 
as for typescript we are still discussing it, we do want to refactor the code but that is for next year
we are not sold on typescript yet as it will make the library unnecessarily hard for js developers and beginners
and that is our focus , to make an approachable modular library that any JS developer can modify and use

**Comment by KeshavJha2002** [comment]
"I am interested in contributing to this codebase by migrating all the JavaScript code to TypeScript. If given the opportunity, I would be enthusiastic to take on this task as part of an open-source project."
