### ISSUE TITLE
New URL for Record payment in invoice page

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#382]
@onfranciis please add different page url for Record payment in invoice page
<img width="1039" alt="Screenshot 2023-08-31 at 1 29 27 PM" src="https://github.com/idurar/idurar-erp-crm/assets/136928179/549f78bb-0b43-4f12-9c80-6679e39c17c0">

**Comment by SahilAgrwl** [comment]
plz assig this issue to me
