### ISSUE TITLE
feat: Show "Not Found" Message for Invoices and Quotes when Attempting to Read or Update Non-Existent Documents.

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#388]
1- "Not Found" Message for Invoices/Quotes: Currently, there is no feedback when users try to read/update non-existent documents. We need to show a "Not Found" message to inform the user that the document doesn't exist.

2- Back Button to Invoice/Quote List: There is no easy way to go back to the list view after viewing an individual Invoice/Quote. We need to add a back button for easy navigation between individual documents and the list view.

**Comment by SahilAgrwl** [comment]
plz assign this issue to me

**Comment by salahlalami** [comment]
@SahilAgrwl you can work on it , please fork from dev branch

**Comment by SahilAgrwl** [comment]
Ok, I started working on it.

**Comment by rkmdCodes** [comment]
hi @salahlalami sir
can you please give more insights about this issue,
willing to work on this

Thanks

**Comment by salahlalami** [comment]
@rkmdCodes , try to test the app to understund , when use go to invoice/update/:id , if we couldn't found docs we need to show not found message

**Comment by onfranciis** [comment]
@rkmdCodes and @SahilAgrwl don't work on the back button feature anymore. Just focus on the 404 feature

**Comment by salahlalami** [comment]
the issue is resolved
