### ISSUE TITLE
feat: Add icon burger button to close Side  left Panel (on top)

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#421]
<img width="1357" alt="Screenshot 2023-09-04 at 11 29 52 PM" src="https://github.com/idurar/idurar-erp-crm/assets/136928179/0c2b5e7e-0e19-4837-a77d-88dd1ad329be">

**Comment by sahith29s** [comment]
Can I work on this issue.

**Comment by rkmdCodes** [comment]
hi @salahlalami 
I have opened a PR #425 which will close this issue 
Thanks

https://github.com/idurar/idurar-erp-crm/assets/113243168/fb314de3-b00e-42f2-bcab-369122929fab
