### ISSUE TITLE
Icons Misalignment In Notifications Bar

### ISSUE THREAD

**Issue by ShatilKhan** [idurar/idurar-erp-crm#430]
Currently when pressing the Notification Icon, The `delete` buttons are not aligned

![Idurar](https://github.com/idurar/idurar-erp-crm/assets/52494840/4b3e4e9c-f841-4d8c-a4b5-e1cb39542ec3)

I am going to be working on this to fix the alignment.

**Comment by polymahh** [comment]
this is already fixed please update ur branch
