### ISSUE TITLE
Remove delete option from dashboard

### ISSUE THREAD

**Issue by onfranciis** [idurar/idurar-erp-crm#474]
**Describe the bug**
Remove the delete option from the dashboard's recent dropdown

**To Reproduce**
1. Go to 'dashboard'
2. Scroll down to recent section
3. Click any of the row's option

**Expected behavior**
- Delete option should not be there

**Screenshots**
![Screenshot from 2023-09-07 00-05-59](https://github.com/idurar/idurar-erp-crm/assets/96952305/ac000f05-70a4-4a05-bd40-be4a175d6ba9)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Edge Beta
 - Version:  115.0.1901.183 (Official build) beta (64-bit)

**Comment by Neeraja-Gadi** [comment]
can i contributeto this?  I can fix this
