### ISSUE TITLE
Update status of [entity] when saved

### ISSUE THREAD

**Issue by onfranciis** [idurar/idurar-erp-crm#476]
**Describe the bug**
When the status field of /[entity]/update/[id] is updated and saved, the header UI does not reflect it.

**To Reproduce**
1. Go to '/[entity]/update/[id]'
2. Change the form 'status'
3. Save it

**Expected behavior**
The coloured status text should update

**Screenshots**
![Screenshot from 2023-09-07 01-26-28](https://github.com/idurar/idurar-erp-crm/assets/96952305/f4ecc37c-fce5-4e59-8f94-49d2d1251320)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Edge Beta
 - Version : 115.0.1901.183 (Official build) beta (64-bit)

**Comment by Gaurav01Kumar** [comment]
Fixed/update status of entity when quote will update  476  #477
