### ISSUE TITLE
Offer page not working 

### ISSUE THREAD

**Issue by AIABHISHEK** [idurar/idurar-erp-crm#579]
**Describe the bug**
When we click Offer button in navigation everything is removed from page

**To Reproduce**
1. Go to Dashboard
2. Click on Offer Button

**Video**
https://www.loom.com/share/b4c77f887d4f4144a17b64e05d651e67?sid=3393dbae-92eb-4766-b421-62a312591a19

**Desktop**
 - windows 11
 - Chrome
 -Version 117.0.5938.132 (Official Build) (64-bit)

**Comment by aakarshit-agarwal** [comment]
I'm not able to reproduce this, it working fine for me with exact same version of Chrome.

**Comment by AIABHISHEK** [comment]
## This is error I am getting in console
![image](https://github.com/idurar/erp-crm/assets/77627849/12faf42d-a667-4952-a016-59d6ce54cfed)
![image](https://github.com/idurar/erp-crm/assets/77627849/4ca19fb9-faf5-4231-a4b5-b40d721f92f9)

**Comment by Vaibhav91one** [comment]
Can I work on this issue

**Comment by ojongclinton** [comment]
I can work on this issue

**Comment by inesmrad** [comment]
i tried to reproduce the bg with idurar 4.0.0-beta.3, windows 10 as my os and a chrome version  123.0.6312.59.I was able to create an offer in a normal way.

**Comment by AIABHISHEK** [comment]
Issue was in previous versions It is resolved I am closing this issue.
