### ISSUE TITLE
migrate backEnd to TS

### ISSUE THREAD

**Issue by erfuuan** [idurar/idurar-erp-crm#627]
I've been learning TypeScript for a while. Would you be open to me rewriting the project's backend using a simple TypeScript script?

**Comment by lukasz1mroz** [comment]
Hi @erfuuan, you might be interested in this task too #427

**Comment by erfuuan** [comment]
thanks

**Comment by AbdurRKhalid** [comment]
@lukasz1mroz Can you assign this task to me, I am looking forward to make this migration.
