### ISSUE TITLE
Add 🇦🇱 Albanian Language

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#663]
Add New more missed Languages , check video below :

please add new pr for each language

https://www.youtube.com/watch?v=CbqGqOObniQ

**Comment by Vishrut19** [comment]
Hey @salahlalami! When I am trying to add Albanian. It is throwing the below error
<img width="759" alt="Screenshot 2023-11-09 at 2 04 47 PM" src="https://github.com/idurar/idurar-erp-crm/assets/53470896/41e24364-9f47-4ec4-bec5-c7a0a367512e">
Saying that sq_AL doesn't exists. How to fix it?

**Comment by salahlalami** [comment]
it like there is no albanian language in antd , we need to close this issue .

@Vishrut19 Thank you

**Comment by Vishrut19** [comment]
Thanks for letting me know
