### ISSUE TITLE
Add 🇮🇷 Persian  Language in React.js App

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#684]
Add New more missed Languages , check video below :

please add new pr for each language

https://www.youtube.com/watch?v=CbqGqOObniQ

**Comment by sshubham681** [comment]
working on this

**Comment by tommm2** [comment]
@salahlalami Does this issue still need to be resolved?

**Comment by salahlalami** [comment]
@tommm2 yes it is still open
