### ISSUE TITLE
Add 🇵🇱 Polish  Language in React.js App

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#685]
Add New more missed Languages , check video below :

please add new pr for each language

https://www.youtube.com/watch?v=CbqGqOObniQ

**Comment by lukasz1mroz** [comment]
PR #710 

By the way, don't we want to update translation for the left side of index page as well?

<img width="1488" alt="Screenshot 2023-11-04 at 8 37 58" src="https://github.com/idurar/idurar-erp-crm/assets/45930931/4c55f678-8cf4-4baa-bbd0-ffd5c8f972bb">
