### ISSUE TITLE
Add 🇷🇸 Serbian  Language in React.js App

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#687]
Add New more missed Languages , check video below :

please add new pr for each language

https://www.youtube.com/watch?v=CbqGqOObniQ

**Comment by TejaChilumula** [comment]
Hello salahlalami, I want work on this issue, could you please assign it to me.

**Comment by salahlalami** [comment]
@TejaChilumula sure , you can work on it
