### ISSUE TITLE
Add 🇸🇰 Slovak  Language in React.js App

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#688]
Add New more missed Languages , check video below :

please add new pr for each language

https://www.youtube.com/watch?v=CbqGqOObniQ

**Comment by SOUMOJIT-CHAKRABORTY** [comment]
@salahlalami Should I create a pull request?

**Comment by salahlalami** [comment]
@SOUMOJIT-CHAKRABORTY yes create new pr for each new language

**Comment by SOUMOJIT-CHAKRABORTY** [comment]
@salahlalami raised the PR
