### ISSUE TITLE
Add 🇰🇪 Swahili  Language in React.js App

### ISSUE THREAD

**Issue by salahlalami** [idurar/idurar-erp-crm#690]
Add New more missed Languages , check video below :

please add new pr for each language

https://www.youtube.com/watch?v=CbqGqOObniQ

**Comment by OmariJuma** [comment]
@salahlalami this is my first issue that I want to contribute to, can you assign it to me?

**Comment by Babithkp** [comment]
#717 please review and merge if all are okay

**Comment by Babithkp** [comment]
Added Swahili language please review and merge if all are okay #717
