### ISSUE TITLE
Create a better user friendly UI/UX interface in Navigation bar

### ISSUE THREAD

**Issue by yashp4858** [idurar/idurar-erp-crm#813]
![before](https://github.com/idurar/idurar-erp-crm/assets/84620183/f49d069a-199d-4243-91a5-8346828c9de9)

 issue: The circled text "Advanced Settings" was partially invisible from the bottom. 

solution: we can increased the padding from the bottom to get text "Advanced Settings" visible properly.

**Comment by yashp4858** [comment]
@salahlalami can i work on this issue ?

**Comment by salahlalami** [comment]
@yashp4858 ok , we can do

**Comment by yashp4858** [comment]
@salahlalami should i close this issue as you merged the PR of mine for this issue.
