### ISSUE TITLE
Containerization of frontend and backend.

### ISSUE THREAD

**Issue by Ankish-Nayak** [idurar/idurar-erp-crm#814]
1. Containerization of backend and frontend with separate Docker file for each, using docker-compose for creating network between them.
2. Better developer experience and easier app deployment.
3. Readme should be changed in accordance to docker then.

@salahlalami what is your thoughts and can I work on this?

**Comment by salahlalami** [comment]
@Ankish-Nayak we found that we don't need docker , we want to keep our repo clean and simple as much as possible.

we did it before with docker , but it create many confusing when we try to deploy on cloud

Thank you for suggestion
