### ISSUE TITLE
isLoggedIn dose not update

### ISSUE THREAD

**Issue by Ankish-Nayak** [idurar/idurar-erp-crm#817]
When admin or entity is logged out from all sessions or sessions get expired isLoggedIn field should update.

![isLoggedBefore](https://github.com/idurar/idurar-erp-crm/assets/54697799/89d3603d-bf87-476b-8042-65282eb93050)

Logged out from all session still isLoggedIn field not updated.

![isLoggedAfter](https://github.com/idurar/idurar-erp-crm/assets/54697799/26513b27-42ed-4496-a623-e860f5fce454)

@salahlalami please tell me is it valid issue? if it so, can I work on this??

**Comment by Ankish-Nayak** [comment]
@Ando22 need your insight on this is it a valid issue? Or isLoggedIn field used for something else??

**Comment by salahlalami** [comment]
@Ankish-Nayak this is deprecated , we will remove it from schema

**Comment by Ankish-Nayak** [comment]
Schema  got updated and isLoggedIn has been removed.

![Screenshot from 2023-11-19 09-18-55](https://github.com/idurar/idurar-erp-crm/assets/54697799/e3d1efd5-2990-43bb-9fe4-51e3a5f8a494)
