### ISSUE TITLE
Show first 5 clients while Client field is blank on invoice creation page

### ISSUE THREAD

**Issue by rajatpandey441** [idurar/idurar-erp-crm#828]
**Is your feature request related to a problem? Please describe.**
While creating invoice, I am clicking on Client field and it is showing that there is no Customer. After typing few characters of existing customer, I can see existing client. The dropdown should show at least first five clients in the database.

**Describe the solution you'd like**
When Client field is blank, the dropdown should show first five clients available in the database.

**Additional context**
![image](https://github.com/idurar/idurar-erp-crm/assets/20161529/1c2e3333-40fe-4252-9135-752a8c35cc17)

**Comment by rajatpandey441** [comment]
Let me know if I can work on this feature. This change can improve the user experience of the ERP

**Comment by salahlalami** [comment]
@rajatpandey441 that's good idea , add this features please to fetch first 10 , this should be generic

**Comment by rajatpandey441** [comment]
@salahlalami Can you open a seperate ticket for this task and assign it to me? Actually, my coursework requires me to contribute to a open source project. It's mentioned that the issue should be opened by the maintainer. I understand that it doesn't work like this but hope you understand my situation.
