### ISSUE TITLE
Wrong Total after creating a new Invoice

### ISSUE THREAD

**Issue by Ritik2712** [idurar/idurar-erp-crm#852]
**Describe the bug***
I created a new Invoice with subtotal of $264 and a total  of $290. But when I refresh the invoice page it is showing a total of $2904 because it is taking taxtotal as 500% in my case

**To Reproduce**
  1. Go to application
  2. Create an invoice.
  3. Refresh the invoice page

![Screenshot 2023-11-29 130518](https://github.com/idurar/idurar-erp-crm/assets/55313035/9a4d825d-61a1-4b17-a909-6565a2ca4991)
![Screenshot 2023-11-29 130603](https://github.com/idurar/idurar-erp-crm/assets/55313035/3dcb9e6d-1931-49bd-89d3-1cc314bb595a)

**Expected behavior**
As seen in the screen shots the total in the invoice page should be either $290 or $290.4

**Comment by pereriksson** [comment]
I can't reproduce this. How is your VAT configured?

**Comment by Ritik2712** [comment]
I checked and it is resolved in the new build I will close the issue now.
