### ISSUE TITLE
move react project to vite

### ISSUE THREAD

**Issue by pj199611** [idurar/idurar-erp-crm#862]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Vishrut19** [comment]
Can I work on it?

**Comment by dhrumitpatel48** [comment]
@pj199611 What is the need to move the project to Vite ?? As far as I know, Vite is used for lean development. As of now, the setup is perfect.
