### ISSUE TITLE
How do I start contribution in this project?

### ISSUE THREAD

**Issue by im-abdulmannan** [idurar/idurar-erp-crm#907]

**Comment by brunovjk** [comment]
[How to contribute](https://github.com/idurar/idurar-erp-crm/blob/master/CONTRIBUTING.md#how-to-contribute) :)

**Comment by Gregsai** [comment]
Hey, 

I think that you can review this file which explain quite well how to contribute to the project : 

https://github.com/idurar/idurar-erp-crm/blob/master/CONTRIBUTING.md
