### ISSUE TITLE
Can i use local install MongoDB?

### ISSUE THREAD

**Issue by kirilovsasha** [idurar/idurar-erp-crm#940]
Hi, Can i use local install MongoDB or use docker? Thanx.

**Comment by Gregsai** [comment]
Hey, 

Local installation of MongoDB (MongoDB Compass) should work. 

Follow "Getting Started" guidelines in the [README.md](https://github.com/idurar/idurar-erp-crm/blob/master/README.md) and at the step 4, just use your local mongoDB URI (e.g.  "mongodb://localhost:27017/{Your database name}" ) that you can find launching MongoDB Compass. 

And you should be fine for the last steps. 

Hope it'll help.

**Comment by kirilovsasha** [comment]
Thank you.
