### ISSUE TITLE
PLease create docker file and docker-compose.yml file with proper instruction so that people can selfhost this easily without issues

### ISSUE THREAD

**Issue by HakaishinShwet** [idurar/idurar-erp-crm#948]
:-)

**Comment by HakaishinShwet** [comment]
i have seen some comments regarding same request and i must say that running with docker is much more easy if provided one simple docker-compose.yml file and person has to chnage 3-4 parameters like port and networking stuff and he can run easily plus can use nginx reverse proxy manager to locally run with proper ssl certificate on local url :-) so please support docker it is not made to make things complex but to make things easy. who doesnt learn even simple docker basics can run locally if they want to but but docker is pretty great and is been for long time now in market so max will be comfortable with it imo

**Comment by salahlalami** [comment]
@HakaishinShwet i merge this docker PR : https://github.com/idurar/idurar-erp-crm/pull/915

please clone Dev Branch : https://github.com/idurar/idurar-erp-crm/tree/dev

try and let me know if it work

**Comment by HakaishinShwet** [comment]
@salahlalami dev i tested it and i am getting status code 409 error :-(( any idea how can we resolve it rest main page is loading and at time of signup after filling info i am getting this in console. i didnt changed anything except frontend port and aht thing doesnt matter so rest all is same so you can try and reproduce if you want to but if you figure out what can be the cause for then do let me know and i will retry again :-))

ERROR :
auth.service.js:31  POST http://localhost:8888/api/register 409 (Conflict)

**Comment by HakaishinShwet** [comment]
![20240208_09h03m37s_grim](https://github.com/idurar/idurar-erp-crm/assets/55040435/227474ed-7ed1-4035-9684-76fa314cfa62)
![20240208_09h03m24s_grim](https://github.com/idurar/idurar-erp-crm/assets/55040435/55531166-a718-41a3-883b-be1eb30e849f)

**Comment by salahlalami** [comment]
try: 
`npm run setup`

Then login with :

```
email: admin@demo.com
password : admin123
```

**Comment by salahlalami** [comment]
> try: `npm run setup`
> 
> Then login with :
> 
> ```
> email: admin@demo.com
> password : admin123
> ```
