### ISSUE TITLE
Error 400 when trying to add new admin

### ISSUE THREAD

**Issue by ngtalexander** [idurar/idurar-erp-crm#971]
**Describe the bug**
When trying to add a new admin/manager/employee, it says "email or password fields they don't have been entered" 

**To Reproduce**
1. Go to 'https://demo-erp-crm.idurarapp.com/admin'
2. Click on 'Add New Admin'
3. Fill inputs

**Expected behavior**

**Screenshots**
![image](https://github.com/idurar/idurar-erp-crm/assets/156243001/e0c3abeb-04a3-447d-b5f8-90fa3207ae82)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by salahlalami** [comment]
@ngtalexander issue fixed, 
thank your for your contribution
