### ISSUE TITLE
Missing script local in frontend when running with Docker

### ISSUE THREAD

**Issue by Kratemis** [idurar/idurar-erp-crm#985]
**Describe the bug**
Hello,
In Dockerfile, the last line is "npm run local", but if we check package.json, there is not script called local. I don't know if I miss something because I am not an frontend expert, perhaps I forgive a step.

**To Reproduce**
Build frontend and execute it

**Comment by itxTouseef74** [comment]
That issue comes becasue in package.json there is no local there is dev you have to run project by npm run dev. In Docker file you have to make some changes to run this project here is updated Docker file .
